[package]
name = "nhentai"
version = "0.5.16"
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
extension-utils = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
networking = { workspace = true }
scraper = { workspace = true }
serde = { workspace = true }
tanoshi-lib = { workspace = true }
url = "2"
urlencoding = { workspace = true }

[dev-dependencies]
extension-utils = { workspace = true, features = ["test-support"] }
