[workspace]
resolver = "3"
members = ["extensions/*", "common/*"]
exclude = [
    "extensions/dead",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1"
bytes = "1"
chrono = "0.4"
extension-utils = { path = "common/extension-utils" }
lazy_static = "1"
log = "0.4"
networking = { path = "common/networking" }
scraper = "0.24"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tanoshi-lib = { git = "https://github.com/luigi311/tanoshi", tag = "v0.38.0" }
urlencoding = "2.1.3"

[profile.release]
strip = true
opt-level = "z"
lto = true
