[package]
name = "weebcentral"
version = "0.5.13"
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
extension-utils = { workspace = true }
log = { workspace = true }
networking = { workspace = true }
scraper = { workspace = true }
tanoshi-lib = { workspace = true }

[dev-dependencies]
extension-utils = { workspace = true, features = ["test-support"] }
