[package]
name = "weebcentral"
version = "0.5.8"
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
extension-utils = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
networking = { workspace = true }
scraper = { workspace = true }
tanoshi-lib = { workspace = true }
urlencoding = { workspace = true }
