[package]
name = "mangadex"
version = "0.5.10"
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
extension-utils = { workspace = true }
fancy-regex = "0.16"
lazy_static = { workspace = true }
log = { workspace = true }
networking = { workspace = true }
phf = { version = "0.13", features = ["macros"] }
serde = { workspace = true }
serde_qs = "0.15"
tanoshi-lib = { workspace = true }
url = "2"

[dev-dependencies]
extension-utils = { workspace = true, features = ["test-support"] }
