[package]
name = "mangadex"
version = "0.5.13"
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
extension-utils = { workspace = true }
fancy-regex = "0.16"
log = { workspace = true }
networking = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_qs = "0.15"
tanoshi-lib = { workspace = true }
url = "2"

[dev-dependencies]
extension-utils = { workspace = true, features = ["test-support"] }
