[package]
name = "guya"
version = "0.5.11"
edition.workspace = true


[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
extension-utils = { workspace = true }
guyalib = { path = "../../common/guyalib" }
lazy_static = { workspace = true }
log = { workspace = true }
networking = { workspace = true }
tanoshi-lib = { workspace = true }

[dev-dependencies]
extension-utils = { workspace = true, features = ["test-support"] }
