[package]
name = "manhwa18cc"
version = "0.5.8"
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
extension-utils = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
madara = { path = "../../common/madara" }
networking = { workspace = true }
scraper = { workspace = true }
tanoshi-lib = { workspace = true }

[dev-dependencies]
extension-utils = { workspace = true, features = ["test-support"] }
